### ISSUE TITLE
More memes in slides needed

### ISSUE THREAD

**Issue by laboon** [laboon/CS1632_Summer2017#1]
SUMMARY:
DESCRIPTION:
REPRO
....

**Comment by jeh170** [comment]
![image](https://user-images.githubusercontent.com/19557637/27089456-5ed72ec6-5028-11e7-8089-6407ee709cc9.png)

**Comment by jeh170** [comment]
![image](https://user-images.githubusercontent.com/19557637/27089487-78343e2c-5028-11e7-90e0-5811b152df36.png)

**Comment by jeh170** [comment]
![image](https://user-images.githubusercontent.com/19557637/27090032-13251180-502a-11e7-872e-588dc5f04ec5.png)

**Comment by jeh170** [comment]
![image](https://user-images.githubusercontent.com/19557637/27090080-35a4ad7e-502a-11e7-9f1d-8b5268c5758d.png)

**Comment by jeh170** [comment]
![image](https://user-images.githubusercontent.com/19557637/27091687-e09a37c2-502e-11e7-8502-8480f878e143.png)

**Comment by laboon** [comment]
All good. Next semester...
